# COLORS
COLOR_PURPLE = (130,40,76)
COLOR_GREEN  = (20,255,57)
COLOR_BLACK  = (0,0,0)
COLOR_RED    = (0,0,255)

##################################

# COLOR TO PLOT
COLOR_SPACE_FREE     = COLOR_GREEN 
COLOR_SPACE_NOT_FREE = COLOR_RED 
COLOR_EDGES = COLOR_BLACK

#PATHS
DATA_PATH = "../Data/"
RESULTS_PATH = "../Results/"


